### ISSUE TITLE
issue to run ./SRNS_real/run.sh

### ISSUE THREAD

**Issue by laos1984** [dingjingtao/SRNS#4]
File "SRNS_main.py", line 174, in training
    score_cand_nxt[4] = np.delete(score_cand_nxt[4], list(range(5)), 0)
  File "<__array_function__ internals>", line 6, in delete
  .../function_base.py", line 4552, in delete
    keep[obj,] = False
IndexError: index 1 is out of bounds for axis 0 with size 1

Do you have any idea about the issue?

In the first epoch, the shape of score_cand_nxt[4] is (1, 6028, 3000)
And after the second epoch, the shape of it becomes (2, 6028, 3000)
And so on. Is it correct?

**Comment by QuanYuhan** [comment]
Thanks for your attention
1.We have confirmed that this is a bug caused by numpy versions. In older versions of numpy, this line of code will throw a warning instead of an error. We will update our code soon to avoid this bug.
2.It's correct

**Comment by QuanYuhan** [comment]
#

> Thanks for your attention 1.We have confirmed that this is a bug caused by numpy versions. In older versions of numpy, this line of code will throw a warning instead of an error. We will update our code soon to avoid this bug.

#5
